### ISSUE TITLE
how to change the language?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.blender.Blender#5] opened 2017-12-03 13:26 UTC

**Comment by LeandroStanger** [comment] 2017-12-03 13:26
@nedrichards Could help

**Comment by bochecha** [comment] 2017-12-03 14:12
Thanks for the bug report, I hadn't realized there was an issue with languages.

So there seems to be a problem with the way locales are set up in the flatpak:

```
$ LANG=fr_FR.UTF-8 flatpak run org.blender.Blender 
Warning: Falling back to the standard locale ("C")
```

Not sure what's going on here...

**Comment by bochecha** [comment] 2018-02-18 08:50
So the language files do seem to be present, e.g `/var/lib/flatpak/app/org.blender.Blender/current/active/files/share/blender/2.79/datafiles/locale/fr/LC_MESSAGES/blender.mo`

Maybe it's because they get mounted as `/app/share/blender/2.79/datafiles/locale` and Blender searches for them in `/usr/share/blender/2.79/datafiles/locale`…

**Comment by bochecha** [comment] 2018-05-18 21:05
Alright, so with the latest build from Flathub, I do not get the warning I used to have.

I've also just tested the Fedora package, running it as follows:

```
$ LC_ALL=fr_FR.UTF-8 blender
```

And the UI still is in English.

I tried the exact same command with the official build from https://www.blender.org/download/

```
$ LC_ALL=fr_FR.UTF-8 ./blender
```

And the UI is still in English.

---

However, I found that in `File` -> `User Preferences` -> `System`, you can tick the `International Fonts` checkbox.

At this point, new settings appear:

* `Language`, where you can select a language;
* `Translate`, where you can tell Blender to translate the `Interface`, `Tooltips` and `New Data` into the language selected just above;

And that actually changes the language for the whole UI.

So the languages work fine.

@brechtvl Hi there! Is that the way Blender is supposed to work? It really doesn't automatically pick up the locale, like every other app, and the user is expected to change the language themselves?

**Comment by brechtvl** [comment] 2018-05-18 22:06
Yes, it's not great, but that's how it works at the moment.

**Comment by bochecha** [comment] 2018-05-19 07:51
Ok. It's a bit surprising and I wish I had known that before spending multiple hours investigating this issue…

But thank you very much for confirming.

I really appreciate your taking the time to come and help every time I have needed it. :slightly_smiling_face:

---

Since everything is working as designed upstream, I'm closing this issue.

**Closed** 2018-05-19 07:54 UTC

**Comment by nedrichards** [comment] 2018-05-20 16:30
@bochecha does that mean we should disable split locales for this manifest?

**Comment by bochecha** [comment] 2018-05-20 16:33
@nedrichards There aren't any split locales already, as there is no `.Locale` extension:

```
$ flatpak remote-ls --all flathub | rg blender
org.blender.Blender
org.blender.Blender.Debug
org.blender.Blender.Sources
```

**Comment by nedrichards** [comment] 2018-05-20 16:33
Carry on :-)
